server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: liukun
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: springcloud_server #应用名称
mybatis:
  type-aliases-package: com.dlsp.springcloud_server.mapper
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: localhost # 指定自己的ip信息，不指定的话会自己寻找